<?php

/*
|--------------------------------------------------------------------------
| Images
|--------------------------------------------------------------------------
*/

return [
    'logo'                  => '/images/logo-dtgo.png',
    'head_heartwork'        => '/images/heartwork/head-heartwork.jpg',
    'head_heartwork_mobile' => '/images/heartwork/head-heartwork-mobile.jpg',
    'pic_1'                 => '/images/heartwork/member/pic-1.png',
    'pic_2'                 => '/images/heartwork/member/pic-2.png',
    'pic_3'                 => '/images/heartwork/member/pic-3.png',
    'pic_4'                 => '/images/heartwork/member/pic-4.png',
    'pic_5'                 => '/images/heartwork/member/pic-5.png',
    'pic_6'                 => '/images/heartwork/member/pic-6.png',
    'pic_7'                 => '/images/heartwork/member/pic-7.png',
    'pic_8'                 => '/images/heartwork/member/pic-8.png',
    'pic_9'                 => '/images/heartwork/member/pic-9.png',
    'pic_10'                => '/images/heartwork/member/pic-10.png',
    'profile_image_1'       => '/images/heartwork/profile/01-kittinan.jpg',
    'profile_image_2'       => '/images/heartwork/profile/02-chirapa.jpg',
    'profile_image_3'       => '/images/heartwork/profile/03-natenapis.jpg',
    'profile_image_4'       => '/images/heartwork/profile/04-chaweewan.jpg',
    'profile_image_5'       => '/images/heartwork/profile/05-surachet.jpg',
    'profile_image_6'       => '/images/heartwork/profile/06-nongkarn.jpg',
    'profile_image_7'       => '/images/heartwork/profile/07-veeravith.jpg',
    'profile_image_8'       => '/images/heartwork/profile/08-isara.jpg',
    'profile_image_9'       => '/images/heartwork/profile/09-nittaya.jpg',
    'profile_image_10'      => '/images/heartwork/profile/10-thitirat.jpg',
    'profile_image_11'      => '/images/heartwork/profile/11-netchanok.jpg',
    'profile_image_12'      => '/images/heartwork/profile/12-panadda.jpg',
    'profile_image_13'      => '/images/heartwork/profile/13-parisa.jpg',
    'profile_image_14'      => '/images/heartwork/profile/14-wisuth.jpg',
    'profile_image_15'      => '/images/heartwork/profile/15-methinee.jpg',
    'profile_image_16'      => '/images/heartwork/profile/16-anchisa.jpg',
    'profile_image_17'      => '/images/heartwork/profile/17-phiriyaphon.jpg',
    'profile_image_18'      => '/images/heartwork/profile/18-surachart.jpg',
    'profile_image_19'      => '/images/heartwork/profile/19-daranphop.jpg',
    'profile_image_20'      => '/images/heartwork/profile/20-chinothai.jpg',
    'profile_image_21'      => '/images/heartwork/profile/21-tossaporn.jpg',
    'profile_image_22'      => '/images/heartwork/profile/22-songpol.jpg',
    'profile_image_23'      => '/images/heartwork/profile/23-sutawan.jpg',
    'profile_image_24'      => '/images/heartwork/profile/24-pornchanok.jpg',
    'profile_image_25'      => '/images/heartwork/profile/25-wichitta.jpg',
    'profile_image_26'      => '/images/heartwork/profile/26-charkrit.jpg',
    'profile_image_27'      => '/images/heartwork/profile/27-napajorn.jpg',
    'profile_image_28'      => '/images/heartwork/profile/28-supanna.jpg',
    'profile_image_29'      => '/images/heartwork/profile/29-worarat.jpg',
    'profile_image_30'      => '/images/heartwork/profile/30-sethawat.jpg',
    'profile_image_31'      => '/images/heartwork/profile/31-thanakorn.jpg',
    'profile_image_32'      => '/images/heartwork/profile/32-nichapa.jpg',
    'profile_image_33'      => '/images/heartwork/profile/33-somsak.jpg',

    'background_1'  => '/images/heartwork/background/01-kittinan-t.jpg',
    'background_2'  => '/images/heartwork/background/02-chirapa-t.jpg',
    'background_3'  => '/images/heartwork/background/03-natenapis-t.jpg',
    'background_4'  => '/images/heartwork/background/04-chaweewan-t.jpg',
    'background_5'  => '/images/heartwork/background/05-surachet-t.jpg',
    'background_6'  => '/images/heartwork/background/06-nongkarn-t.jpg',
    'background_7'  => '/images/heartwork/background/07-veeravith-t.jpg',
    'background_8'  => '/images/heartwork/background/08-isara-t.jpg',
    'background_9'  => '/images/heartwork/background/09-nittaya-t.jpg',
    'background_10' => '/images/heartwork/background/10-thitirat-t.jpg',
    'background_11' => '/images/heartwork/background/11-netchanok-t.jpg',
    'background_12' => '/images/heartwork/background/12-panadda-t.jpg',
    'background_13' => '/images/heartwork/background/13-parisa-t.jpg',
    'background_14' => '/images/heartwork/background/14-wisuth-t.jpg',
    'background_15' => '/images/heartwork/background/15-methinee-t.jpg',
    'background_16' => '/images/heartwork/background/16-anchisa-t.jpg',
    'background_17' => '/images/heartwork/background/17-phiriyaphon-t.jpg',
    'background_18' => '/images/heartwork/background/18-surachart-t.jpg',
    'background_19' => '/images/heartwork/background/19-daranphop-t.jpg',
    'background_20' => '/images/heartwork/background/20-chinothai-t.jpg',
    'background_21' => '/images/heartwork/background/21-tossaporn-t.jpg',
    'background_22' => '/images/heartwork/background/22-songpol-t.jpg',
    'background_23' => '/images/heartwork/background/23-sutawan-t.jpg',
    'background_24' => '/images/heartwork/background/24-pornchanok-t.jpg',
    'background_25' => '/images/heartwork/background/25-wichitta.jpg',
    'background_26' => '/images/heartwork/background/26-charkrit-t.jpg',
    'background_27' => '/images/heartwork/background/27-napajorn-t.jpg',
    'background_28' => '/images/heartwork/background/28-supanna-t.jpg',
    'background_29' => '/images/heartwork/background/29-worarat-t.jpg',
    'background_30' => '/images/heartwork/background/30-sethawat-t.jpg',
    'background_31' => '/images/heartwork/background/31-thanakorn-t.jpg',
    'background_32' => '/images/heartwork/background/32-nichapa-t.jpg',
    'background_33' => '/images/heartwork/background/33-somsak-t.jpg',

    'quote_1'  => '/images/heartwork/quote/01-kittinan-f.jpg',
    'quote_2'  => '/images/heartwork/quote/02-chirapa-f.jpg',
    'quote_3'  => '/images/heartwork/quote/03-natenapis-f.jpg',
    'quote_4'  => '/images/heartwork/quote/04-chaweewan-f.jpg',
    'quote_5'  => '/images/heartwork/quote/05-surachet-f.jpg',
    'quote_6'  => '/images/heartwork/quote/06-nongkarn-f.jpg',
    'quote_7'  => '/images/heartwork/quote/07-veeravith-f.jpg',
    'quote_8'  => '/images/heartwork/quote/08-isara-f.jpg',
    'quote_9'  => '/images/heartwork/quote/09-nittaya-f.jpg',
    'quote_10' => '/images/heartwork/quote/10-thitirat-f.jpg',
    'quote_11' => '/images/heartwork/quote/11-netchanok-f.jpg',
    'quote_12' => '/images/heartwork/quote/12-panadda-f.jpg',
    'quote_13' => '/images/heartwork/quote/13-parisa-f.jpg',
    'quote_14' => '/images/heartwork/quote/14-wisuth-f.jpg',
    'quote_15' => '/images/heartwork/quote/15-methinee-f.jpg',
    'quote_16' => '/images/heartwork/quote/16-anchisa-f.jpg',
    'quote_17' => '/images/heartwork/quote/17-phiriyaphon-f.jpg',
    'quote_18' => '/images/heartwork/quote/18-surachart-f.jpg',
    'quote_19' => '/images/heartwork/quote/19-daranphop-f.jpg',
    'quote_20' => '/images/heartwork/quote/20-chinothai-f.jpg',
    'quote_21' => '/images/heartwork/quote/21-tossaporn-f.jpg',
    'quote_22' => '/images/heartwork/quote/22-songpol-f.jpg',
    'quote_23' => '/images/heartwork/quote/23-sutawan-f.jpg',
    'quote_24' => '/images/heartwork/quote/24-pornchanok-f.jpg',
    'quote_25' => '/images/heartwork/quote/25-wichitta-f.jpg',
    'quote_26' => '/images/heartwork/quote/26-charkrit-f.jpg',
    'quote_27' => '/images/heartwork/quote/27-napajorn-f.jpg',
    'quote_28' => '/images/heartwork/quote/28-supanna-f.jpg',
    'quote_29' => '/images/heartwork/quote/29-worarat-f.jpg',
    'quote_30' => '/images/heartwork/quote/30-sethawat-f.jpg',
    'quote_31' => '/images/heartwork/quote/31-thanakorn-f.jpg',
    'quote_32' => '/images/heartwork/quote/32-nichapa-f.jpg',
    'quote_33' => '/images/heartwork/quote/33-somsak-f.jpg',

    'quote_topic' => '/images/heartwork/quote-topic.png',

];